from typing import List

GLOBALS = {}

#globals
GLOBALS["FILENAME"] = None
GLOBALS["BUFFER"]: List[str] = None #lines of the opened file
GLOBALS["LINE_BUFFER_LEFT"]: str = None
GLOBALS["LINE_BUFFER_RIGHT"]: str = None
GLOBALS["LINE_INDEX"]: int = 0
GLOBALS["COLUMN_INDEX"]: List[int] = None
GLOBALS["LINE_LENGTH"]: int = None
GLOBALS["NEW_LINE_LENGTH"]: int = None
GLOBALS["NUMBER_OF_DIGITS"]: int = None
GLOBALS["IS_FILE_SAVED"]:bool = None

#KEY CODES
GLOBALS["ESCAPE_KEY"] = b"\x1b"
GLOBALS["SAVE_KEY"] = b"\x13"
GLOBALS["WIN_DELETE_KEY"] = b"\x08"
GLOBALS["WIN_CURSOR_KEY"] = b"\xe0"
GLOBALS["WIN_LEFT_ARROW_KEY"] = "K"
GLOBALS["WIN_RIGHT_ARROW_KEY"] = "M"
GLOBALS["WIN_BOTTOM_ARROW_KEY"] = "P"
GLOBALS["WIN_TOP_ARROW_KEY"] = "H"
GLOBALS["WIN_END_KEY"] = "O"
GLOBALS["WIN_BEGINING_KEY"] = "G"
GLOBALS["WIN_CTRL_LEFT_ARROW_KEY"] = "s"
GLOBALS["WIN_CTRL_RIGHT_ARROW_KEY"] = "t"
GLOBALS["LINUX_LEFT_ARROW_KEY"] = "D"
GLOBALS["LINUX_RIGHT_ARROW_KEY"] = "C"
GLOBALS["LINUX_BOTTOM_ARROW_KEY"] = "B"
GLOBALS["LINUX_TOP_ARROW_KEY"] = "A"
GLOBALS["LINUX_END_KEY"] = "F"
GLOBALS["LINUX_BEGINING_KEY"] = "H"
GLOBALS["LINUX_CTRL_LEFT_ARROW_KEY"] = ";5D"
GLOBALS["LINUX_CTRL_RIGHT_ARROW_KEY"] = ";5C"
GLOBALS["LINUX_DELETE_KEY"] = b"\x7f"
GLOBALS["NEWLINE_KEY"] = b"\r"
GLOBALS["TAB_KEY"] = b"\t"
GLOBALS["CTRL_K_KEY"] = b"\x0b"
GLOBALS["CTRL_P_KEY"] = b"\x10"
GLOBALS["CTRL_L_KEY"] = b"\x0c"
GLOBALS["CTRL_O_KEY"] = b"\x0f"
GLOBALS["CTRL_W_KEY"] = b"\x17"
GLOBALS["CTRL_Q_KEY"] = b"\x11"
GLOBALS["CTRL_D_KEY"] = b"\x04"