from typing import List

GLOBALS = {}

#globals
GLOBALS["FILENAME"] = None
GLOBALS["BUFFER"]: List[str] = None #lines of the opened file
GLOBALS["LINE_BUFFER_LEFT"]: str = None
GLOBALS["LINE_BUFFER_RIGHT"]: str = None
GLOBALS["LINE_INDEX"]: int = 0
GLOBALS["COLUMN_INDEX"]: List[int] = None
GLOBALS["LINE_LENGTH"]: int = None
GLOBALS["NEW_LINE_LENGTH"]: int = None
GLOBALS["NUMBER_OF_DIGITS"]: int = None
GLOBALS["IS_FILE_SAVED"]:bool = None

#KEY CODES
GLOBALS["SAVE_KEY"] = b"\x13"
GLOBALS["CURSOR_KEY"] = b"\xe0"
GLOBALS["LEFT_ARROW_KEY"] = "K"
GLOBALS["RIGHT_ARROW_KEY"] = "M"
GLOBALS["BOTTOM_ARROW_KEY"] = "P"
GLOBALS["TOP_ARROW_KEY"] = "H"
GLOBALS["END_KEY"] = "O"
GLOBALS["BEGINING_KEY"] = "G"
GLOBALS["CTRL_LEFT_ARROW_KEY"] = "s"
GLOBALS["CTRL_RIGHT_ARROW_KEY"] = "t"
GLOBALS["DELETE_KEY"] = b"\x08"
GLOBALS["NEWLINE_KEY"] = b"\r"
GLOBALS["TAB_KEY"] = b"\t"
GLOBALS["CTRL_K_KEY"] = b"\x0b"
GLOBALS["CTRL_P_KEY"] = b"\x10"
GLOBALS["CTRL_L_KEY"] = b"\x0c"
GLOBALS["CTRL_O_KEY"] = b"\x0f"
GLOBALS["CTRL_W_KEY"] = b"\x17"
GLOBALS["CTRL_Q_KEY"] = b"\x11"
GLOBALS["CTRL_D_KEY"] = b"\x04"